import type { Locale } from "@/lib/i18n/config";

// ══════════════════════════════════════════════════════════
//  Mapa de contenidos del blog.
//
//  No es una lista de ideas: es la arquitectura de autoridad temática. Cada
//  entrada declara su clúster, su intención de búsqueda, su fase del embudo y
//  a qué curso empuja, para que el enlazado interno y la prioridad de
//  producción se decidan con criterio y no por orden de ocurrencia.
//
//  Las versiones en inglés NO son traducciones: son artículos propios con
//  keywords del mercado angloparlante, donde la competencia y el vocabulario
//  son distintos ("employer of record" pesa mucho más que su equivalente
//  español; "autónomo" no tiene traducción útil).
//
//  Reglas del proyecto que afectan a todo lo que se escriba aquí:
//   · Prohibido usar "gratis", "gratuito", "free", "sin coste" y variantes en
//     URL, títulos, encabezados, meta, FAQ, CTA, schema, ALT y anchor.
//   · Cada sección abre con una respuesta directa de 40-60 palabras.
//   · Cada bloque tiene que entenderse aislado: es lo que se cita.
// ══════════════════════════════════════════════════════════

export type Cluster =
  | "empleo"
  | "fiscalidad"
  | "legal"
  | "negocio"
  | "metodo"
  | "herramientas";

/** Fase del embudo. Decide el CTA y cuánto se puede empujar el curso. */
export type Funnel = "tofu" | "mofu" | "bofu";

/** Intención de búsqueda dominante en la SERP. */
export type Intent = "informacional" | "comercial" | "transaccional" | "navegacional";

export type ArticleSpec = {
  slug: string;
  locale: Locale;
  cluster: Cluster;
  funnel: Funnel;
  intent: Intent;
  /** Keyword principal, tal cual se busca. */
  keyword: string;
  /** Long tail que debe cubrir el artículo. */
  longTail: string[];
  title: string;
  /** 1 = producir primero. Pondera intención comercial y cercanía al curso. */
  priority: 1 | 2 | 3;
  /** A qué curso empuja, si empuja a alguno. */
  course?: "remote-professional" | "remote-founder";
  /** Términos del diccionario que este artículo debe enlazar. */
  terms: string[];
  /** Slugs del mismo idioma con los que se enlaza en ambos sentidos. */
  links: string[];
  status: "publicado" | "borrador" | "planificado";
};

// ── Español ──────────────────────────────────────────────
export const MAP_ES: readonly ArticleSpec[] = [
  {
    slug: "trabajo-remoto-internacional-desde-espana",
    locale: "es",
    cluster: "empleo",
    funnel: "mofu",
    intent: "comercial",
    keyword: "trabajo remoto internacional desde España",
    longTail: [
      "cómo conseguir un trabajo remoto para una empresa extranjera",
      "trabajar para una empresa de Estados Unidos desde España",
      "empleo remoto internacional requisitos",
    ],
    title: "Trabajo remoto internacional desde España: la guía completa de 2026",
    priority: 1,
    course: "remote-professional",
    terms: ["trabajo-remoto", "solapamiento-horario", "employer-of-record", "contractor-internacional"],
    links: ["como-trabajar-para-empresa-extranjera-legalmente", "cv-internacional-ats", "solapamiento-horario-ofertas-remotas"],
    status: "publicado",
  },
  {
    slug: "como-trabajar-para-empresa-extranjera-legalmente",
    locale: "es",
    cluster: "legal",
    funnel: "mofu",
    intent: "informacional",
    keyword: "cómo trabajar para una empresa extranjera legalmente",
    longTail: [
      "contrato para trabajar en remoto para empresa extranjera",
      "employer of record qué es y cuándo se usa",
      "ser contractor de una empresa de fuera",
    ],
    title: "Cómo trabajar para una empresa extranjera sin meterte en un lío legal",
    priority: 1,
    course: "remote-professional",
    terms: ["employer-of-record", "contractor-internacional", "falso-autonomo", "nomina-internacional"],
    links: ["trabajo-remoto-internacional-desde-espana", "residencia-fiscal-nomada-digital"],
    status: "publicado",
  },
  {
    slug: "cv-internacional-ats",
    locale: "es",
    cluster: "empleo",
    funnel: "mofu",
    intent: "informacional",
    keyword: "currículum internacional ATS",
    longTail: [
      "cómo hacer un cv que pase el filtro ats",
      "cv en inglés para empresa extranjera",
      "por qué me rechazan sin leer mi currículum",
    ],
    title: "El currículum que pasa el ATS: qué cambia cuando aplicas fuera",
    priority: 1,
    course: "remote-professional",
    terms: ["ats", "cv-internacional", "portfolio-internacional"],
    links: ["trabajo-remoto-internacional-desde-espana", "portfolio-para-recruiters-internacionales"],
    status: "publicado",
  },
  {
    slug: "residencia-fiscal-nomada-digital",
    locale: "es",
    cluster: "fiscalidad",
    funnel: "mofu",
    intent: "informacional",
    keyword: "residencia fiscal nómada digital",
    longTail: [
      "regla de los 183 días cómo funciona",
      "dónde tributo si trabajo en remoto desde otro país",
      "perder la residencia fiscal en España",
    ],
    title: "Residencia fiscal para nómadas digitales: los 183 días no son lo que crees",
    priority: 1,
    terms: ["residencia-fiscal", "regla-183-dias", "doble-imposicion", "nomada-digital"],
    links: ["visados-nomada-digital-comparativa", "como-trabajar-para-empresa-extranjera-legalmente"],
    status: "publicado",
  },
  {
    slug: "visados-nomada-digital-comparativa",
    locale: "es",
    cluster: "fiscalidad",
    funnel: "tofu",
    intent: "informacional",
    keyword: "visado nómada digital comparativa",
    longTail: [
      "mejores países con visado de nómada digital",
      "requisitos visado nómada digital España",
      "cuánto hay que ingresar para un visado de nómada digital",
    ],
    title: "Visados de nómada digital: qué piden de verdad y a quién le compensan",
    priority: 2,
    terms: ["visado-nomada-digital", "nomada-digital", "residencia-fiscal"],
    links: ["residencia-fiscal-nomada-digital"],
    status: "publicado",
  },
  {
    slug: "negociar-salario-remoto-internacional",
    locale: "es",
    cluster: "empleo",
    funnel: "bofu",
    intent: "comercial",
    keyword: "negociar salario trabajo remoto internacional",
    longTail: [
      "cuánto pedir en una empresa extranjera",
      "salario ajustado por ubicación qué es",
      "cómo negociar compensación global",
    ],
    title: "Negociar un salario remoto internacional sin regalar el 30%",
    priority: 1,
    course: "remote-professional",
    terms: ["compensacion-global", "geo-pay", "multidivisa"],
    links: ["trabajo-remoto-internacional-desde-espana", "cv-internacional-ats"],
    status: "publicado",
  },
  {
    slug: "solapamiento-horario-ofertas-remotas",
    locale: "es",
    cluster: "empleo",
    funnel: "tofu",
    intent: "informacional",
    keyword: "solapamiento horario ofertas remotas",
    longTail: [
      "qué significa overlap en una oferta de trabajo",
      "trabajar con horario de estados unidos desde europa",
    ],
    title: "El requisito que te descarta sin que lo leas: el solapamiento horario",
    priority: 2,
    course: "remote-professional",
    terms: ["solapamiento-horario", "trabajo-asincrono", "burnout-remoto"],
    links: ["trabajo-remoto-internacional-desde-espana", "trabajo-asincrono-guia"],
    status: "publicado",
  },
  {
    slug: "portfolio-para-recruiters-internacionales",
    locale: "es",
    cluster: "empleo",
    funnel: "mofu",
    intent: "informacional",
    keyword: "portfolio profesional internacional",
    longTail: ["cómo hacer un portfolio si no soy diseñador", "qué poner en un portfolio profesional"],
    title: "Un portfolio que convence a quien no conoce tus empresas",
    priority: 2,
    course: "remote-professional",
    terms: ["portfolio-internacional", "marca-personal", "cv-internacional"],
    links: ["cv-internacional-ats", "marca-personal-tecnica"],
    status: "publicado",
  },
  {
    slug: "entrevista-remota-video-asincrona",
    locale: "es",
    cluster: "empleo",
    funnel: "mofu",
    intent: "informacional",
    keyword: "entrevista de trabajo remota en vídeo",
    longTail: ["prueba técnica asíncrona", "cómo preparar una entrevista en inglés en vídeo"],
    title: "La entrevista remota se gana antes de encenderse la cámara",
    priority: 2,
    course: "remote-professional",
    terms: ["trabajo-asincrono", "onboarding-distribuido"],
    links: ["cv-internacional-ats", "negociar-salario-remoto-internacional"],
    status: "publicado",
  },
  {
    slug: "primeros-90-dias-equipo-distribuido",
    locale: "es",
    cluster: "metodo",
    funnel: "tofu",
    intent: "informacional",
    keyword: "primeros 90 días trabajo remoto",
    longTail: ["onboarding remoto qué esperar", "cómo destacar en un equipo distribuido"],
    title: "Tus primeros 90 días en un equipo distribuido",
    priority: 3,
    course: "remote-professional",
    terms: ["onboarding-distribuido", "documentacion-asincrona", "trabajo-asincrono"],
    links: ["trabajo-asincrono-guia", "burnout-remoto-senales"],
    status: "publicado",
  },
  {
    slug: "trabajo-asincrono-guia",
    locale: "es",
    cluster: "metodo",
    funnel: "tofu",
    intent: "informacional",
    keyword: "trabajo asíncrono qué es",
    longTail: ["comunicación asíncrona ejemplos", "cómo trabajar en asíncrono con husos distintos"],
    title: "Trabajo asíncrono: la diferencia entre estar en remoto y funcionar en remoto",
    priority: 2,
    terms: ["trabajo-asincrono", "documentacion-asincrona", "solapamiento-horario", "stack-remoto"],
    links: ["solapamiento-horario-ofertas-remotas", "stack-remoto-imprescindible"],
    status: "publicado",
  },
  {
    slug: "burnout-remoto-senales",
    locale: "es",
    cluster: "metodo",
    funnel: "tofu",
    intent: "informacional",
    keyword: "burnout trabajo remoto señales",
    longTail: ["agotamiento teletrabajo qué hacer", "poner límites trabajando en remoto"],
    title: "Burnout remoto: las señales que aparecen antes del cansancio",
    priority: 3,
    terms: ["burnout-remoto", "solapamiento-horario", "trabajo-asincrono"],
    links: ["trabajo-asincrono-guia", "primeros-90-dias-equipo-distribuido"],
    status: "publicado",
  },
  {
    slug: "stack-remoto-imprescindible",
    locale: "es",
    cluster: "herramientas",
    funnel: "tofu",
    intent: "informacional",
    keyword: "herramientas trabajo remoto",
    longTail: ["mejores herramientas para equipos distribuidos", "stack de trabajo remoto"],
    title: "El stack remoto mínimo: 12 herramientas y ninguna de más",
    priority: 2,
    terms: ["stack-remoto", "documentacion-asincrona", "automatizacion-no-code"],
    links: ["trabajo-asincrono-guia", "automatizar-negocio-sin-codigo"],
    status: "publicado",
  },
  {
    slug: "ia-para-buscar-trabajo-remoto",
    locale: "es",
    cluster: "herramientas",
    funnel: "mofu",
    intent: "comercial",
    keyword: "usar IA para buscar trabajo",
    longTail: ["chatgpt para adaptar el currículum", "prompts para preparar entrevistas"],
    title: "IA para buscar trabajo remoto: lo que funciona y lo que te delata",
    priority: 1,
    course: "remote-professional",
    terms: ["prompt-engineering", "agente-ia", "ats", "cv-internacional"],
    links: ["cv-internacional-ats", "stack-remoto-imprescindible"],
    status: "publicado",
  },
  {
    slug: "de-freelance-a-negocio-productizado",
    locale: "es",
    cluster: "negocio",
    funnel: "mofu",
    intent: "comercial",
    keyword: "dejar de cobrar por horas",
    longTail: ["servicio productizado ejemplos", "cómo escalar como freelance sin contratar"],
    title: "Dejar de cobrar por horas: el salto de freelance a negocio",
    priority: 1,
    course: "remote-founder",
    terms: ["oferta-productizada", "solopreneur", "negocio-borderless", "sop"],
    links: ["conseguir-clientes-b2b-internacionales", "automatizar-negocio-sin-codigo"],
    status: "publicado",
  },
  {
    slug: "conseguir-clientes-b2b-internacionales",
    locale: "es",
    cluster: "negocio",
    funnel: "bofu",
    intent: "comercial",
    keyword: "conseguir clientes internacionales",
    longTail: ["captar clientes b2b en el extranjero", "cold email que funciona 2026"],
    title: "Conseguir clientes B2B internacionales sin red de contactos",
    priority: 1,
    course: "remote-founder",
    terms: ["negocio-borderless", "oferta-productizada", "marca-personal"],
    links: ["de-freelance-a-negocio-productizado", "cobrar-clientes-extranjero"],
    status: "publicado",
  },
  {
    slug: "cobrar-clientes-extranjero",
    locale: "es",
    cluster: "fiscalidad",
    funnel: "mofu",
    intent: "informacional",
    keyword: "cómo cobrar de clientes extranjeros",
    longTail: ["facturar a empresa de estados unidos desde españa", "cuenta multidivisa autónomos"],
    title: "Cobrar de clientes extranjeros sin perder el 4% por el camino",
    priority: 1,
    course: "remote-founder",
    terms: ["facturacion-internacional", "multidivisa", "contractor-internacional"],
    links: ["conseguir-clientes-b2b-internacionales", "como-trabajar-para-empresa-extranjera-legalmente"],
    status: "publicado",
  },
  {
    slug: "automatizar-negocio-sin-codigo",
    locale: "es",
    cluster: "herramientas",
    funnel: "mofu",
    intent: "informacional",
    keyword: "automatizar negocio sin código",
    longTail: ["make vs zapier vs n8n", "automatizaciones para freelance"],
    title: "Automatizar tu negocio sin código: qué automatizar y en qué orden",
    priority: 2,
    course: "remote-founder",
    terms: ["automatizacion-no-code", "sop", "agente-ia", "solopreneur"],
    links: ["de-freelance-a-negocio-productizado", "stack-remoto-imprescindible"],
    status: "publicado",
  },
  {
    slug: "sop-documentar-procesos",
    locale: "es",
    cluster: "negocio",
    funnel: "tofu",
    intent: "informacional",
    keyword: "cómo documentar procesos SOP",
    longTail: ["plantilla de sop", "documentar para delegar"],
    title: "SOPs: documentar un proceso para poder soltarlo",
    priority: 3,
    course: "remote-founder",
    terms: ["sop", "documentacion-asincrona", "automatizacion-no-code"],
    links: ["automatizar-negocio-sin-codigo", "de-freelance-a-negocio-productizado"],
    status: "publicado",
  },
  {
    slug: "curso-trabajo-remoto-cual-elegir",
    locale: "es",
    cluster: "empleo",
    funnel: "bofu",
    intent: "comercial",
    keyword: "curso de trabajo remoto cuál elegir",
    longTail: ["formación en trabajo remoto internacional", "merece la pena un curso de nómada digital"],
    title: "Cursos de trabajo remoto: cómo distinguir formación de humo",
    priority: 1,
    terms: ["trabajo-remoto", "negocio-borderless", "employer-of-record"],
    links: ["trabajo-remoto-internacional-desde-espana", "de-freelance-a-negocio-productizado"],
    status: "publicado",
  },
];

// ── English ──────────────────────────────────────────────
export const MAP_EN: readonly ArticleSpec[] = [
  {
    slug: "international-remote-jobs-from-europe",
    locale: "en",
    cluster: "empleo",
    funnel: "mofu",
    intent: "comercial",
    keyword: "international remote jobs from europe",
    longTail: [
      "how to get a us remote job from europe",
      "remote jobs that hire internationally",
      "work for a us company from abroad",
    ],
    title: "International Remote Jobs From Europe: What Actually Gets You Hired",
    priority: 1,
    course: "remote-professional",
    terms: ["trabajo-remoto", "solapamiento-horario", "employer-of-record"],
    links: ["employer-of-record-vs-contractor", "ats-friendly-resume", "time-zone-overlap-explained"],
    status: "publicado",
  },
  {
    slug: "employer-of-record-vs-contractor",
    locale: "en",
    cluster: "legal",
    funnel: "mofu",
    intent: "comercial",
    keyword: "employer of record vs contractor",
    longTail: ["what is an employer of record", "eor vs peo difference", "should i be a contractor or employee"],
    title: "Employer of Record vs Contractor: Which One Should You Sign?",
    priority: 1,
    course: "remote-professional",
    terms: ["employer-of-record", "contractor-internacional", "falso-autonomo", "nomina-internacional"],
    links: ["international-remote-jobs-from-europe", "worker-misclassification-risk"],
    status: "publicado",
  },
  {
    slug: "ats-friendly-resume",
    locale: "en",
    cluster: "empleo",
    funnel: "mofu",
    intent: "informacional",
    keyword: "ats friendly resume",
    longTail: ["how to beat applicant tracking systems", "resume format that passes ats", "why am i not getting interviews"],
    title: "The ATS-Friendly Resume: What Machines Read Before Humans Do",
    priority: 1,
    course: "remote-professional",
    terms: ["ats", "cv-internacional", "portfolio-internacional"],
    links: ["international-remote-jobs-from-europe", "proof-of-work-portfolio"],
    status: "publicado",
  },
  {
    slug: "tax-residency-remote-workers",
    locale: "en",
    cluster: "fiscalidad",
    funnel: "mofu",
    intent: "informacional",
    keyword: "tax residency for remote workers",
    longTail: ["183 day rule explained", "where do i pay tax if i work remotely", "digital nomad tax residency"],
    title: "Tax Residency for Remote Workers: The 183-Day Rule Is a Trap",
    priority: 1,
    terms: ["residencia-fiscal", "regla-183-dias", "doble-imposicion"],
    links: ["digital-nomad-visa-comparison", "employer-of-record-vs-contractor"],
    status: "publicado",
  },
  {
    slug: "digital-nomad-visa-comparison",
    locale: "en",
    cluster: "fiscalidad",
    funnel: "tofu",
    intent: "informacional",
    keyword: "digital nomad visa comparison",
    longTail: ["best digital nomad visas 2026", "digital nomad visa income requirement"],
    title: "Digital Nomad Visas Compared: Income Thresholds and Hidden Catches",
    priority: 2,
    terms: ["visado-nomada-digital", "nomada-digital", "residencia-fiscal"],
    links: ["tax-residency-remote-workers"],
    status: "publicado",
  },
  {
    slug: "negotiating-remote-salary",
    locale: "en",
    cluster: "empleo",
    funnel: "bofu",
    intent: "comercial",
    keyword: "negotiating remote salary",
    longTail: ["location based pay explained", "how to negotiate total compensation", "remote salary bands"],
    title: "Negotiating a Remote Salary When the Company Pays by Location",
    priority: 1,
    course: "remote-professional",
    terms: ["compensacion-global", "geo-pay", "multidivisa"],
    links: ["international-remote-jobs-from-europe", "ats-friendly-resume"],
    status: "publicado",
  },
  {
    slug: "time-zone-overlap-explained",
    locale: "en",
    cluster: "empleo",
    funnel: "tofu",
    intent: "informacional",
    keyword: "time zone overlap remote job",
    longTail: ["what does overlap hours mean", "working us hours from europe"],
    title: "Time Zone Overlap: The Requirement That Filters You Out Silently",
    priority: 2,
    course: "remote-professional",
    terms: ["solapamiento-horario", "trabajo-asincrono", "burnout-remoto"],
    links: ["international-remote-jobs-from-europe", "async-work-guide"],
    status: "publicado",
  },
  {
    slug: "proof-of-work-portfolio",
    locale: "en",
    cluster: "empleo",
    funnel: "mofu",
    intent: "informacional",
    keyword: "portfolio for remote job",
    longTail: ["proof of work portfolio examples", "portfolio for non designers"],
    title: "A Portfolio That Works When Nobody Knows Your Employers",
    priority: 2,
    course: "remote-professional",
    terms: ["portfolio-internacional", "marca-personal", "cv-internacional"],
    links: ["ats-friendly-resume", "personal-brand-for-engineers"],
    status: "publicado",
  },
  {
    slug: "async-interview-and-video-screening",
    locale: "en",
    cluster: "empleo",
    funnel: "mofu",
    intent: "informacional",
    keyword: "async interview remote job",
    longTail: ["one way video interview tips", "take home assignment remote job"],
    title: "Async Interviews and Video Screens: How Remote Hiring Really Filters",
    priority: 2,
    course: "remote-professional",
    terms: ["trabajo-asincrono", "onboarding-distribuido"],
    links: ["ats-friendly-resume", "negotiating-remote-salary"],
    status: "publicado",
  },
  {
    slug: "first-90-days-remote-team",
    locale: "en",
    cluster: "metodo",
    funnel: "tofu",
    intent: "informacional",
    keyword: "first 90 days remote job",
    longTail: ["remote onboarding checklist", "how to stand out in a distributed team"],
    title: "Your First 90 Days on a Distributed Team",
    priority: 3,
    course: "remote-professional",
    terms: ["onboarding-distribuido", "documentacion-asincrona"],
    links: ["async-work-guide", "remote-burnout-signals"],
    status: "publicado",
  },
  {
    slug: "async-work-guide",
    locale: "en",
    cluster: "metodo",
    funnel: "tofu",
    intent: "informacional",
    keyword: "asynchronous work",
    longTail: ["async communication examples", "how to run an async team"],
    title: "Asynchronous Work: The Difference Between Being Remote and Working Remotely",
    priority: 2,
    terms: ["trabajo-asincrono", "documentacion-asincrona", "solapamiento-horario"],
    links: ["time-zone-overlap-explained", "remote-work-stack"],
    status: "publicado",
  },
  {
    slug: "remote-burnout-signals",
    locale: "en",
    cluster: "metodo",
    funnel: "tofu",
    intent: "informacional",
    keyword: "remote work burnout signs",
    longTail: ["setting boundaries working remotely", "always on culture remote"],
    title: "Remote Burnout: The Signals That Show Up Before Exhaustion",
    priority: 3,
    terms: ["burnout-remoto", "solapamiento-horario"],
    links: ["async-work-guide", "first-90-days-remote-team"],
    status: "publicado",
  },
  {
    slug: "remote-work-stack",
    locale: "en",
    cluster: "herramientas",
    funnel: "tofu",
    intent: "informacional",
    keyword: "remote work tools",
    longTail: ["best tools for distributed teams", "remote work tech stack"],
    title: "The Minimum Remote Stack: 12 Tools and Not One More",
    priority: 2,
    terms: ["stack-remoto", "documentacion-asincrona", "automatizacion-no-code"],
    links: ["async-work-guide", "no-code-automation-for-solopreneurs"],
    status: "publicado",
  },
  {
    slug: "ai-for-job-search",
    locale: "en",
    cluster: "herramientas",
    funnel: "mofu",
    intent: "comercial",
    keyword: "ai for job search",
    longTail: ["chatgpt resume tailoring", "ai interview preparation prompts"],
    title: "AI for the Job Search: What Helps and What Gets You Caught",
    priority: 1,
    course: "remote-professional",
    terms: ["prompt-engineering", "agente-ia", "ats"],
    links: ["ats-friendly-resume", "remote-work-stack"],
    status: "publicado",
  },
  {
    slug: "productised-service-business",
    locale: "en",
    cluster: "negocio",
    funnel: "mofu",
    intent: "comercial",
    keyword: "productised service business",
    longTail: ["stop charging hourly", "productized service examples", "scale freelance without hiring"],
    title: "Stop Charging by the Hour: Turning a Service Into a Product",
    priority: 1,
    course: "remote-founder",
    terms: ["oferta-productizada", "solopreneur", "negocio-borderless"],
    links: ["b2b-clients-without-network", "no-code-automation-for-solopreneurs"],
    status: "publicado",
  },
  {
    slug: "b2b-clients-without-network",
    locale: "en",
    cluster: "negocio",
    funnel: "bofu",
    intent: "comercial",
    keyword: "get b2b clients internationally",
    longTail: ["cold email b2b 2026", "finding international clients as a freelancer"],
    title: "Landing International B2B Clients With No Network",
    priority: 1,
    course: "remote-founder",
    terms: ["negocio-borderless", "oferta-productizada", "marca-personal"],
    links: ["productised-service-business", "getting-paid-internationally"],
    status: "publicado",
  },
  {
    slug: "getting-paid-internationally",
    locale: "en",
    cluster: "fiscalidad",
    funnel: "mofu",
    intent: "informacional",
    keyword: "getting paid by international clients",
    longTail: ["invoice a us company from europe", "multi currency account freelancer"],
    title: "Getting Paid by International Clients Without Losing 4% on the Way",
    priority: 1,
    course: "remote-founder",
    terms: ["facturacion-internacional", "multidivisa", "contractor-internacional"],
    links: ["b2b-clients-without-network", "employer-of-record-vs-contractor"],
    status: "publicado",
  },
  {
    slug: "no-code-automation-for-solopreneurs",
    locale: "en",
    cluster: "herramientas",
    funnel: "mofu",
    intent: "informacional",
    keyword: "no code automation for business",
    longTail: ["make vs zapier vs n8n", "automations for freelancers"],
    title: "No-Code Automation: What to Automate, and in Which Order",
    priority: 2,
    course: "remote-founder",
    terms: ["automatizacion-no-code", "sop", "agente-ia"],
    links: ["productised-service-business", "remote-work-stack"],
    status: "publicado",
  },
  {
    slug: "writing-sops-to-delegate",
    locale: "en",
    cluster: "negocio",
    funnel: "tofu",
    intent: "informacional",
    keyword: "how to write sops",
    longTail: ["sop template small business", "documenting processes to delegate"],
    title: "Writing SOPs You Can Actually Hand Over",
    priority: 3,
    course: "remote-founder",
    terms: ["sop", "documentacion-asincrona"],
    links: ["no-code-automation-for-solopreneurs", "productised-service-business"],
    status: "publicado",
  },
  {
    slug: "worker-misclassification-risk",
    locale: "en",
    cluster: "legal",
    funnel: "mofu",
    intent: "informacional",
    keyword: "worker misclassification remote",
    longTail: ["contractor vs employee test", "misclassification penalties remote hiring"],
    title: "Misclassification: When a Contractor Is Really an Employee",
    priority: 2,
    terms: ["falso-autonomo", "contractor-internacional", "employer-of-record"],
    links: ["employer-of-record-vs-contractor", "getting-paid-internationally"],
    status: "publicado",
  },
];

export const CONTENT_MAP: Record<Locale, readonly ArticleSpec[]> = {
  es: MAP_ES,
  en: MAP_EN,
};

/** Pares equivalentes ES↔EN, para las etiquetas hreflang. */
export const HREFLANG_PAIRS: Record<string, string> = {
  "trabajo-remoto-internacional-desde-espana": "international-remote-jobs-from-europe",
  "como-trabajar-para-empresa-extranjera-legalmente": "employer-of-record-vs-contractor",
  "cv-internacional-ats": "ats-friendly-resume",
  "residencia-fiscal-nomada-digital": "tax-residency-remote-workers",
  "visados-nomada-digital-comparativa": "digital-nomad-visa-comparison",
  "negociar-salario-remoto-internacional": "negotiating-remote-salary",
  "solapamiento-horario-ofertas-remotas": "time-zone-overlap-explained",
  "portfolio-para-recruiters-internacionales": "proof-of-work-portfolio",
  "entrevista-remota-video-asincrona": "async-interview-and-video-screening",
  "primeros-90-dias-equipo-distribuido": "first-90-days-remote-team",
  "trabajo-asincrono-guia": "async-work-guide",
  "burnout-remoto-senales": "remote-burnout-signals",
  "stack-remoto-imprescindible": "remote-work-stack",
  "ia-para-buscar-trabajo-remoto": "ai-for-job-search",
  "de-freelance-a-negocio-productizado": "productised-service-business",
  "conseguir-clientes-b2b-internacionales": "b2b-clients-without-network",
  "cobrar-clientes-extranjero": "getting-paid-internationally",
  "automatizar-negocio-sin-codigo": "no-code-automation-for-solopreneurs",
  "sop-documentar-procesos": "writing-sops-to-delegate",
  "curso-trabajo-remoto-cual-elegir": "worker-misclassification-risk",
};

/** Palabras vetadas en todo el contenido del blog. */
export const BANNED_WORDS = [
  "gratis", "gratuito", "gratuita", "gratuitos", "gratuitas",
  "free", "complimentary", "sin coste", "sin costo",
  "coste cero", "costo cero", "100% gratis",
] as const;
